### PR TITLE
fix: reduced metadata requests and fixed filter issues, fixes #60 #61

### LINKED ISSUE #60: Filter issues when typing fast
When you type quickly in the new metric dialog, the filter sometimes gets bugged.

Screenshot_2021-05-07_11-34-01
(This screenshot was taken a good long while after I finished typing)

I can reproduce this pretty contistently

I *suspect*, that the responses to the selection overtake each other, i.e. the response to `elab.a` arrives *after* `elab.ar` and therefore the list doesn't match the currently typed filter.

The requests should still be sent in parallel to reduce latency, but you probably have to somehow sequentialize processing the requests and discard replies that belong to requests where a more recent request has already been answered.

### PR DESCRIPTION
**Pull request by AndyBuchwald**

### CODE REVIEW

File: js/MetricHandler.js [hunk 1]
```diff
@@ -137,6 +137,10 @@ export class MetricHandler {
     return this.metricQHistory.search(inputStr)
   }
 
+  searchMetricsPromiseAndMetadata (inputStr) {
```
Comment (tilsche) [inline js/MetricHandler.js:140]: The name is weird. If we were really to stick with the scheme, it would be something like `searchMetricsWithMetadataPromise`. But I'd rather just use the existing `searchMetricsPromise` and add a `metadata` parameter there that's passed through to `search`.

**Review by tilsche — CHANGES_REQUESTED** [review]
I assume this may practically reduce the occurrences for #60, but it does not conceptionally fix it.
I'm afraid #60 may still happen with jittery network connections. For a proper fix, we need to drop now-outdated responses in the promise handling.

**Review by tilsche — APPROVED** [review]
