### PR TITLE
fix: adding an already existing metric now works, fixes #115

### LINKED ISSUE #115: trying to add an already existing metrics results in errors
Trying to add an already metric returns vue error.
Doesn't close new metric popup.
Need to implement a check.

### PR DESCRIPTION
**Pull request by AndyBuchwald**

### CODE REVIEW

**Comment by tilsche** [comment]
Deferred for a little bit to see if we can find a quick solution for notifications/messaging.

File: src/store/metrics.js [hunk 1]
```diff
@@ -119,20 +123,41 @@ export default {
...
+        marker,
+        errorprone,
+        drawMin,
+        drawMax,
+        drawAvg
+      }
+    }) {
       if (state.metrics[name] !== undefined) {
-        throw new Error('Metric already exists!')
+        // throw new Error('Metric already exists!')
```
Comment (tilsche) [inline src/store/metrics.js:140]: please remove
