### PR TITLE
refactor & fix: combines all metrics/create calls into one and checks…

### LINKED ISSUE #144: Deal with metadata errors
It seems the UI gets stuck when invalid metrics are included, e.g. bogus URL.

### PR DESCRIPTION
**Pull request by AndyBuchwald**
… whether metric has metadata, fixes #144

### CODE REVIEW

**Comment by AndyBuchwald** [comment]
also fixes #140

File: src/MetricQWebView.js [hunk 1]
```diff
@@ -218,6 +216,26 @@ class MetricQWebView {
     }, this.RELOAD_THROTTLING_DELAY)
   }
 
+  async addMetric (metricBase, description = undefined, oldMetric = undefined) {
+    try {
+      await this.store.dispatch('metrics/create', { metric: { ...oldMetric, name: metricBase, description: description, traces: [] } })
```
Comment (tilsche) [inline src/MetricQWebView.js:221]: Now the boolean return value of `addMetric` is used, but a bool is never returned here.

**Review by tilsche — CHANGES_REQUESTED** [review]

**Comment by tilsche** [comment]
@AndyBuchwald small hint. If you *rebase* then there is no extra commit. If there's an extra commit, you probably *merged* the `master` into branch
